### ISSUE TITLE
Collision bug and magazine bug.

### ISSUE THREAD

**Issue by mrwallace888** [Maiq-The-Dude/BetterHands#8] opened 2021-08-02 21:35 UTC
I have Easy Mag loading for Palming disabled, and I also have Easy Mag Loading disabled in the game's settings. However, sometimes I occasionally come across a bug where it acts like my palmed items have no collisions anyways. It seems to be spontaneous, I don't know what causes it directly. It includes bullets, too. Sometimes trigger-palmed rounds tend to collide with the gun, other times they phase through like the magazines.

Also, when holding a trigger-palmed round, you can't put it into a gun or a magazine (i.e. top-loading rifles, refilling a gun mag, tube-fed shotguns, etc.). You can put it in the chamber of the gun, but not the magazine.

**Comment by Maiq-The-Dude** [comment] 2021-08-03 18:20
Your first issue is intended behavior to prevent collision bugs and noise clanks, you can disable it entirely via `CollisionPrevention` in the config or increase the velocity at which it triggers with `CollisionPreventionVelocity `.

Your second issue is because rounds palmed in the betterhands slot only supports loading directly into chambers. I could look into adding support to load into magazines next time I'm working on a new feature.

**Comment by Maiq-The-Dude** [comment] 2021-08-04 18:12
A round in a BH slot can now be loaded into magazines or clips in [Update 1.5.0](https://github.com/Maiq-The-Dude/BetterHands/releases/tag/1.5.0)

**Comment by Maiq-The-Dude** [comment] 2021-08-05 02:39
Can you upload your config file? Also can you confirm the config is listed as `maiq.Betterhands` in r2mm. Thanks

**Comment by mrwallace888** [comment] 2021-08-05 02:46
[Here you go.](https://drive.google.com/file/d/1QI5lp_heJ8srl8SZEe9oXQY6UENKGSpF/view?usp=sharing)

**Comment by Maiq-The-Dude** [comment] 2021-08-05 03:01
I forgot to ask for the log file, oops. Can you upload that as well please. I know there's no error but it'll hopefully give me something.

**Comment by mrwallace888** [comment] 2021-08-05 03:43
If your DMs were still open on Discord I could sent it there and make this easier. But for now I have to upload stuff to Drive.

[Anyways, here's the log.](https://drive.google.com/file/d/1eYCgr1FWDTXkfLR22PZNUuv9GDgqxqp7/view?usp=sharing)

**Comment by Maiq-The-Dude** [comment] 2021-08-05 04:16
I had to close them but I can add you on it.

**Comment by Maiq-The-Dude** [comment] 2021-11-05 15:57
I think we determined at the time this was being caused by another mod. Closing for now but can be reopened later if new info comes to light

**Closed as completed by Maiq-The-Dude** 2021-11-05 15:57 UTC
Labels: enhancement
